version: "3.9"
services:
  chromadb:
    build:
      context: .
      dockerfile: Dockerfile.db # ChromaDB
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma_data

volumes:
  chroma_data:
