# version: "3.9"
services:
  chromadb:
    build:
      context: .
      dockerfile: Dockerfile.db # ChromaDB
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma_data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000

  fetchai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
    depends_on:
      - chromadb
    restart: unless-stopped

volumes:
  chroma_data:
